name: Deploy FireTrack360 to DigitalOcean

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firetrack360-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      
      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for Backend to Start
        run: |
          sleep 20  # Wait for the backend to fully start and connect to the DB

      - name: Verify Backend Health
        run: |
          HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health || echo "000")
          if [ "$HEALTH_CHECK" != "200" ]; then
            echo "Health check failed. HTTP status: $HEALTH_CHECK"
            docker logs fire_extinguisher_backend
            exit 1
          fi
          echo "Deployment successful!"
