name: Deploy FireTrack360 to DigitalOcean
on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firetrack360-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      - name: Deploy to DigitalOcean
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{secrets.DB_NAME}}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Pull and run the Docker container
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/firetrack360-backend:latest
            docker stop firetrack360-backend || true
            docker rm firetrack360-backend || true
            docker run -d \
              --name firetrack360-backend \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/firetrack360-backend:latest
      
      - name: Verify Container Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Wait for container to start
            sleep 20
            
            # Check container status
            CONTAINER_STATUS=$(docker inspect -f '{{.State.Status}}' firetrack360-backend)
            if [ "$CONTAINER_STATUS" != "running" ]; then
              echo "Container is not running"
              docker logs firetrack360-backend
              exit 1
            fi
            
            # Perform health check
            HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health || echo "000")
            if [ "$HEALTH_CHECK" != "200" ]; then
              echo "Health check failed. HTTP status: $HEALTH_CHECK"
              docker logs firetrack360-backend
              exit 1
            fi
            
            echo "Deployment successful!"