name: Deploy FireTrack360 to DigitalOcean
on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firetrack360-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,env.production"
          target: "/root/firetrack360"

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /root/firetrack360
            
            # Copy env.production to .env
            cp env.production .env
            
            # Pull latest images and restart containers
            docker compose pull
            docker compose down
            docker compose up -d

            # Wait for services to be healthy
            echo "Waiting for services to be healthy..."
            sleep 30

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /root/firetrack360
            
            # Check containers status
            BACKEND_STATUS=$(docker compose ps backend --format json | grep -o '"State":"[^"]*"' | cut -d'"' -f4)
            if [ "$BACKEND_STATUS" != "running" ]; then
              echo "Backend container is not running"
              docker compose logs backend
              exit 1
            fi

            # Health check
            HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health || echo "000")
            if [ "$HEALTH_CHECK" != "200" ]; then
              echo "Health check failed. HTTP status: $HEALTH_CHECK"
              docker compose logs
              exit 1
            fi

            echo "Deployment successful!"