name: Build FireTrack360

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm run build

      - name: Run Unit Tests
        run: pnpm run test

      - name: Run Linter
        run: pnpm run lint

      - name: Upload Coverage to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
          retention-days: 5